import React,{useState}from"react";import{createRoot}from"react-dom/client";import{Home,Gauge,ClipboardList,Filter,Truck,Mail,Handshake,CalendarDays,BarChart3,LineChart,Download,Search,Car,WalletCards,CircleDollarSign,AlertTriangle,TrendingUp,CheckCircle2,MoreHorizontal,PlusCircle,Send,ShieldCheck,PauseCircle}from"lucide-react";import"./styles.css";
const nav=[["dashboard","Dashboard",Home],["collections","Collections",Gauge],["delinquent","Delinquent Loans",ClipboardList],["pipeline","Recovery Pipeline",Filter],["repossession","Repossession Queue",Truck],["assets","Recovery Assets",Mail],["workouts","Workouts",Handshake],["paymentPlans","Payment Plans",CalendarDays],["reports","Reports",BarChart3],["analytics","Analytics",LineChart]];
const meta={dashboard:["Collections & Recovery Center","Delinquency management and recovery workflow"],collections:["Collections & Recovery Center","Collections operations and borrower outreach management"],delinquent:["Delinquent Loans","Monitor and manage delinquent loan portfolio"],pipeline:["Recovery Pipeline","Track and optimize the recovery process from outreach to resolution"],repossession:["Repossession Queue","Manage and prioritize repossession cases"],assets:["Recovery Assets","Track, manage, and liquidate repossessed collateral assets"],workouts:["Workouts","Manage workout plans and modifications"],paymentPlans:["Payment Plans","Manage repayment arrangements and monitor performance"],reports:["Reports","Analyze portfolio performance and recovery operations"],analytics:["Analytics","Deep insights into collections performance and recovery operations"]};
const rows=[["LOAN-70124","Daniel Brown","2020 Jeep Grand Cherokee",67,"$28,750","60+ Days","High"],["LOAN-66031","Ashley Taylor","2019 Dodge Charger",78,"$26,430","60+ Days","Medium"],["LOAN-54312","Robert Miller","2021 Nissan Altima",91,"$24,120","90+ Days","High"],["LOAN-48219","Jessica Davis","2020 Chevy Silverado",102,"$31,560","90+ Days","Medium"],["LOAN-39002","Michael Johnson","2018 Honda Accord",115,"$21,870","90+ Days","Medium"],["LOAN-33211","Christopher Lee","2019 Toyota Camry",45,"$22,310","30+ Days","Medium"],["LOAN-28765","Amanda Wilson","2021 Ford Explorer",33,"$30,220","30+ Days","Low"],["LOAN-27419","Brandon White","2020 Hyundai Elantra",29,"$18,940","30+ Days","Low"]];
function App(){const[tab,setTab]=useState("dashboard"),[title,sub]=meta[tab];return <div className="app"><aside><div className="brand"><i/>AUTO<span>DEFI</span></div><nav>{nav.map(([id,l,I])=><button onClick={()=>setTab(id)} className={tab===id?"on":""} key={id}><I size={19}/>{l}</button>)}</nav><div className="net"><b>AutoDeFi <span>Network</span></b><p>● Live</p><dl><dt>Active Lenders</dt><dd>1,248</dd><dt>Loans Managed</dt><dd>11,293</dd><dt>Capital Deployed</dt><dd>$78.42M</dd></dl><button>View Network Activity</button></div></aside><main><header><div><h1>{title}</h1><p>{sub}</p></div><div className="tools"><button><CalendarDays size={16}/>May 12, 2025</button><button><Filter size={16}/>Filters</button><button className="blue">View Demo</button><button><Download size={16}/>Export</button></div></header><Screen tab={tab}/></main></div>}
function Screen({tab}){return <><Kpis tab={tab}/>{["delinquent","repossession","workouts","paymentPlans"].includes(tab)&&<FiltersRow/>}{tab==="dashboard"&&<Dashboard/>}{tab==="collections"&&<Collections/>}{tab==="delinquent"&&<Two left={<Table title="Delinquent Loans (1,451)"/>} right={<SideCharts/>}/>} {tab==="pipeline"&&<Pipeline/>}{tab==="repossession"&&<Two left={<Table title="Repossession Cases" prefix="RCV"/>} right={<SideCharts title="Queue Overview"/>}/>} {tab==="assets"&&<Two left={<Table title="Recovery Asset Inventory" prefix="ASSET"/>} right={<SideCharts title="Asset Status Overview"/>}/>} {tab==="workouts"&&<Two left={<Table title="Workouts (248)" prefix="WKT"/>} right={<SideCharts title="Workout Status Breakdown"/>}/>} {tab==="paymentPlans"&&<Two left={<Table title="Payment Plans (624)" prefix="PP"/>} right={<SideCharts title="Plan Status Overview"/>}/>} {tab==="reports"&&<Reports/>}{tab==="analytics"&&<Analytics/>}<Actions tab={tab}/></>}
function Kpis({tab}){let a=tab==="assets"?[[Car,"Total Recovery Assets","248"],[CircleDollarSign,"Estimated Value","$6.72M"],[CheckCircle2,"Ready for Sale","126"],[Truck,"In Transit","28"],[TrendingUp,"Avg. Days","24"]]:tab==="workouts"?[[TrendingUp,"Total Workouts","248"],[ClipboardList,"Active Workouts","163"],[PauseCircle,"On Hold","34"],[CheckCircle2,"Completed","51"],[CircleDollarSign,"Modified Balance","$5.21M"]]:tab==="paymentPlans"?[[WalletCards,"Payment Plans","624"],[CalendarDays,"New Plans","87"],[CircleDollarSign,"Plan Balance","$6.72M"],[CheckCircle2,"Current","498"],[AlertTriangle,"Delinquent","56"]]:[[WalletCards,tab==="collections"?"Collection Accounts":"Delinquent Loans",tab==="collections"?"1,842":"1,451"],[CircleDollarSign,tab==="analytics"?"Collected 30D":"Total Balance",tab==="analytics"?"$1.24M":"$6.72M"],[CalendarDays,"30+ Days","892"],[AlertTriangle,"90+ Days","167"],[TrendingUp,"Recovery Rate","87.6%"]];return <section className="kpis">{a.map(([I,l,v],i)=><article className="card kpi" key={l}><div className={"ico c"+i}><I size={25}/></div><small>{l}</small><b>{v}</b><em>{i===3?"▼":"▲"} {i===3?"6.8":"9.12"}% <span>vs last 30d</span></em></article>)}</section>}
function Dashboard(){return <><div className="grid3"><Panel title="Delinquency Aging"><Donut/></Panel><Panel title="Recovery Pipeline"><Funnel/></Panel><Panel title="Top Recovery Actions"><Bars items={["Payment Plan 72%","Loan Workout 69%","Repossession 91%","Settlement 88%","ZONYCS Liquidation 94%"]}/></Panel></div><Two left={<Table title="Repossession Queue" prefix="RCV"/>} right={<Panel title="Recovery Assets Overview"><Donut center="248" label="Total Assets"/></Panel>}/></>}
function Collections(){return <div className="grid3 wide"><Table title="Collections Queue" prefix="COL"/><Panel title="Outreach Funnel"><Funnel/></Panel><Panel title="Channel Performance"><Bars items={["SMS 48%","Email 33%","Voice Call 28%","In-App 36%","Autopay 25%"]}/></Panel></div>}
function Pipeline(){return <><div className="grid3"><Panel title="Recovery Pipeline Funnel"><Funnel/></Panel><Panel title="Pipeline by Stage"><Bars items={["Contacted 100%","Payment Plan 43%","Workout 17%","Repossession 6%","Liquidation 3%"]}/></Panel><Panel title="Stage Conversion Metrics"><Bars items={["Contacted → Payment Plan 43%","Payment Plan → Workout 40%","Workout → Repossession 36%","Repo → Liquidation 42%"]}/></Panel></div><Table title="Pipeline Accounts (1,451)"/></>}
function Reports(){return <><div className="grid3"><Panel title="Portfolio Performance Trend"><Trend/></Panel><Panel title="Recovery by Channel"><Donut center="$1.24M" label="Total Recovery"/></Panel><Panel title="Recovery Rate by Loan Type"><Bars items={["Retail 92%","Lease 88%","Wholesale 86%","Commercial 73%","Other 65%"]}/></Panel></div><Panel title="Available Reports">{["Executive Summary","Delinquency Analysis","Recovery Performance","Repossession Summary","Workout Performance","Payment Plans Summary","Charge-off Analysis"].map(x=><p className="report" key={x}><b>{x}</b><span>Generated · Download · Email</span></p>)}</Panel></>}
function Analytics(){return <><div className="grid3"><Panel title="Performance Over Time"><Trend/></Panel><Panel title="Recovery Funnel LTM"><Funnel/></Panel><Panel title="Recovery Rate by Channel"><Bars items={["Payment Plan 92%","Workout 89%","Repossession 78%","Settlement 65%","Litigation 29%"]}/></Panel></div><div className="grid3"><Panel title="Delinquency Aging Analysis"><Donut center="$6.72M" label="Total Balance"/></Panel><Panel title="Top Segments"><Bars items={["Retail 92%","Lease 89%","Wholesale 86%","Southeast 88%"]}/></Panel><Panel title="Recovery Heatmap"><div className="heat">{["Retail","Lease","Wholesale","Commercial","Other"].map((r,i)=><p key={r}><b>{r}</b>{[95,90,84,76,62].map((v,j)=><span key={j}>{v-i*2}%</span>)}</p>)}</div></Panel></div></>}
function Panel({title,children}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function Two({left,right}){return <div className="two"><div>{left}</div><div>{right}</div></div>}
function SideCharts({title="Delinquency Aging"}){return <><Panel title={title}><Donut/></Panel><Panel title="Breakdown"><Bars items={["Retail 78%","Wholesale 16%","Lease 7%"]}/></Panel><Panel title="Trend"><Trend/></Panel></>}
function FiltersRow(){return <div className="filters"><div><Search size={17}/> Search borrower, loan ID, vehicle...</div><button>Status: All</button><button>Priority: All</button><button>More Filters</button></div>}
function Table({title,prefix="LOAN"}){return <Panel title={title}><div className="table"><table><tbody>{rows.map(r=><tr key={r[0]}><td className="link">{r[0].replace("LOAN",prefix)}</td><td>{r[1]}</td><td>{r[2]}</td><td className={r[3]>89?"red":r[3]>59?"orange":"blue"}>{r[3]} days</td><td>{r[4]}</td><td><mark>{r[5]}</mark></td><td><mark>{r[6]}</mark></td><td><MoreHorizontal size={17}/></td></tr>)}</tbody></table></div></Panel>}
function Donut({center="1,451",label="Total Loans"}){return <div className="donut"><div/><section><b>{center}</b><small>{label}</small><p><i/>30+ Days 892</p><p><i/>60+ Days 392</p><p><i/>90+ Days 167</p></section></div>}
function Funnel(){return <div className="funnel">{["Contacted 1,451","Payment Plan 624","Workout 248","Repossession 89","Liquidation 37"].map((x,i)=><p style={{width:100-i*10+"%",marginLeft:i*5+"%"}} key={x}>{x}</p>)}<b>Pipeline Conversion: 6.2%</b></div>}
function Bars({items}){return <div className="bars">{items.map(x=>{let n=x.match(/(\d+)%/)?.[1]||"60";return <p key={x}><span>{x}</span><i><em style={{width:n+"%"}}/></i></p>})}</div>}
function Trend(){return <div className="trend">{[48,52,57,61,65,63,69,76].map((h,i)=><i key={i} style={{height:h+"%"}}/> )}</div>}
function Actions({tab}){let a=tab==="assets"?[[Car,"Add Recovery Asset"],[ShieldCheck,"Schedule Inspection"],[Truck,"Assign Transport"],[WalletCards,"List on ZONYCS"]]:tab==="paymentPlans"?[[PlusCircle,"Create Payment Plan"],[CircleDollarSign,"Collect Payment"],[Send,"Send Reminder"]]:[[Mail,"Send Demand"],[CalendarDays,"Create Payment Plan"],[Truck,"Initiate Repossession"],[Handshake,"Workout Loan"],[CircleDollarSign,"Settlement Offer"]];return <div className="actions">{a.map(([I,t])=><button key={t}><I size={25}/><b>{t}</b><small>Open workflow</small></button>)}</div>}
createRoot(document.getElementById("root")).render(<App/>);
