import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Bell, BookOpen, Calendar, Car, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardList, Download, FileText, Globe2, HelpCircle, Home, Landmark, LayoutDashboard, LineChart, LockKeyhole, Mail, MessageCircle, PieChart, Receipt, Search, ShieldCheck, SlidersHorizontal, Sparkles, Target, TrendingUp, Users, Wallet } from 'lucide-react';

type PageKey = 'overview' | 'pools' | 'investments' | 'performance' | 'transactions' | 'statements' | 'reports' | 'portfolio' | 'allocation' | 'yield' | 'payouts' | 'tax' | 'how' | 'risk' | 'docs' | 'help' | 'contact';
type Accent = 'green' | 'blue' | 'purple' | 'orange' | 'cyan' | 'red' | 'slate';
type Metric = { label: string; value: string; change?: string; detail?: string; icon: any; accent: Accent };
type Pool = { name: string; tier: string; risk: string; apy: string; tvl: string; min: string; lock: string; status: string; accent: Accent; description: string };
type Tx = { date: string; type: string; pool: string; amount: string; asset: string; hash: string; status: string };
type Doc = { name: string; type: string; period: string; generated: string; size: string; status: string };

const navGroups: { label: string; items: { key: PageKey; label: string; icon: any }[] }[] = [
  { label: 'Overview', items: [{ key: 'overview', label: 'Overview', icon: Home }] },
  { label: 'Invest', items: [
    { key: 'pools', label: 'Pools', icon: Users }, { key: 'investments', label: 'Investments', icon: Target }, { key: 'performance', label: 'Performance', icon: LineChart },
    { key: 'transactions', label: 'Transactions', icon: Receipt }, { key: 'statements', label: 'Statements', icon: FileText }, { key: 'reports', label: 'Reports', icon: ClipboardList }
  ] },
  { label: 'Portfolio', items: [
    { key: 'portfolio', label: 'My Portfolio', icon: Wallet }, { key: 'allocation', label: 'Allocation', icon: PieChart }, { key: 'yield', label: 'Yield History', icon: TrendingUp },
    { key: 'payouts', label: 'Payouts', icon: Calendar }, { key: 'tax', label: 'Tax Documents', icon: Receipt }
  ] },
  { label: 'Education', items: [
    { key: 'how', label: 'How It Works', icon: HelpCircle }, { key: 'risk', label: 'Risk Framework', icon: ShieldCheck }, { key: 'docs', label: 'Documentation', icon: BookOpen }
  ] },
  { label: 'Support', items: [{ key: 'help', label: 'Help Center', icon: MessageCircle }, { key: 'contact', label: 'Contact Support', icon: Mail }] }
];

const metrics: Metric[] = [
  { label: 'Total Portfolio Value', value: '$12.85M', change: '+14.21%', detail: 'vs last 30d', icon: ShieldCheck, accent: 'green' },
  { label: 'Total Return (YTD)', value: '$1.88M', change: '+18.32%', detail: 'vs last 30d', icon: Sparkles, accent: 'purple' },
  { label: 'Average APY (All Pools)', value: '18.62%', change: '+1.92%', detail: 'vs last 30d', icon: BarChart3, accent: 'green' },
  { label: 'Net Cash Flow', value: '$9.09M', change: '+13.65%', detail: 'vs last 30d', icon: Activity, accent: 'cyan' },
  { label: 'Active Investments', value: '12', detail: 'Across 5 pools', icon: Target, accent: 'blue' }
];

const pools: Pool[] = [
  { name: 'Tier 1 Conservative Pool', tier: 'Tier 1', risk: 'LOW RISK', apy: '12.24%', tvl: '$84.32M', min: '$10,000', lock: '3 Months', status: 'Active', accent: 'green', description: 'Prime loans, low LTV, high credit quality and capital safety.' },
  { name: 'Tier 2 Balanced Pool', tier: 'Tier 2', risk: 'MEDIUM RISK', apy: '18.71%', tvl: '$96.15M', min: '$10,000', lock: '3 Months', status: 'Active', accent: 'blue', description: 'Balanced risk and return across diversified auto finance loans.' },
  { name: 'Tier 3 Aggressive Pool', tier: 'Tier 3', risk: 'HIGH RISK', apy: '25.34%', tvl: '$96.77M', min: '$25,000', lock: '3 Months', status: 'Active', accent: 'purple', description: 'Higher yield, higher risk, optimized for advanced investors.' },
  { name: 'Liquid Staking Pool', tier: 'Staking', risk: 'MEDIUM RISK', apy: '15.82%', tvl: '$1.01M', min: '1,000 ADF', lock: 'Flexible', status: 'Active', accent: 'orange', description: 'Stake ADF and earn protocol yield with liquidity.' },
  { name: 'Cash / Stablecoin Pool', tier: 'Cash', risk: 'LOW RISK', apy: '8.35%', tvl: '$0.50M', min: '$5,000', lock: 'Flexible', status: 'Idle', accent: 'slate', description: 'Low volatility, stable returns, capital preservation.' },
  { name: 'Short Term Opportunities', tier: 'Opportunities', risk: 'MEDIUM RISK', apy: '19.42%', tvl: '$0.42M', min: '$10,000', lock: '1 Month', status: 'Active', accent: 'cyan', description: 'Short-duration auto loans with quick turnover.' }
];

const txs: Tx[] = [
  { date: 'May 12, 2025 10:24 AM', type: 'Deposit', pool: 'Tier 2 Balanced Pool', amount: '$500,000.00', asset: 'USDC', hash: '0x8f3a...b7c9d1e2', status: 'Completed' },
  { date: 'May 8, 2025 02:14 PM', type: 'Deposit', pool: 'Tier 1 Conservative Pool', amount: '$250,000.00', asset: 'USDC', hash: '0x2c1d...a9b8c7d6', status: 'Completed' },
  { date: 'May 6, 2025 09:18 AM', type: 'Payout', pool: 'Tier 3 Aggressive Pool', amount: '$18,742.63', asset: 'USDC', hash: '0x7e9b...c3d4e5f6', status: 'Completed' },
  { date: 'May 5, 2025 12:00 PM', type: 'Rewards', pool: 'Staking Rewards', amount: '2,450.00', asset: 'ADF', hash: '0x4d5e...g7h8i9j0', status: 'Completed' },
  { date: 'Apr 30, 2025 11:02 AM', type: 'Transfer', pool: 'Internal Transfer', amount: '$100,000.00', asset: 'USDC', hash: '0x6f7g...i9j0k1l2', status: 'Completed' }
];

const docs: Doc[] = [
  { name: 'Monthly Performance Summary', type: 'Performance', period: 'Apr 1 – Apr 30, 2025', generated: 'May 12, 2025', size: '2.4 MB', status: 'Completed' },
  { name: 'Q1 2025 Portfolio Summary', type: 'Portfolio', period: 'Jan 1 – Mar 31, 2025', generated: 'Apr 1, 2025', size: '3.1 MB', status: 'Completed' },
  { name: 'Payouts & Rewards Report', type: 'Payout & Rewards', period: 'All Time', generated: 'May 6, 2025', size: '1.8 MB', status: 'Completed' },
  { name: 'Tax Report 2024', type: 'Tax Report', period: 'Jan 1 – Dec 31, 2024', generated: 'Feb 15, 2025', size: '4.7 MB', status: 'Completed' }
];

const lineData = [8, 9, 10, 12, 14, 13, 16, 17, 19, 22, 21, 24, 26, 25, 28, 31, 30, 33];
const blueData = [2, 3, 3, 4, 5, 4, 6, 7, 8, 10, 9, 11, 12, 13, 14, 16, 17, 19];
const bars = [6, 4, 9, 5, 10, 7, 13, 8, 16, 12, 9, 18, 11, 15, 22, 17, 14, 20];

function apiBase() { return import.meta.env.VITE_API_BASE_URL || ''; }
function cx(...names: Array<string | false | undefined>) { return names.filter(Boolean).join(' '); }

function AppIcon({ icon: Icon, accent = 'blue' }: { icon: any; accent?: Accent }) { return <span className={cx('icon-badge', accent)}><Icon size={20} /></span>; }
function Pill({ children, accent = 'green' }: { children: any; accent?: Accent }) { return <span className={cx('pill', accent)}>{children}</span>; }
function Card({ title, children, action }: { title?: string; children: any; action?: any }) { return <section className="card">{title && <div className="card-head"><h2>{title}</h2>{action}</div>}{children}</section>; }
function Metrics({ items = metrics }: { items?: Metric[] }) { return <div className="metrics">{items.map((m) => <article className="metric" key={m.label}><AppIcon icon={m.icon} accent={m.accent}/><div><span>{m.label}</span><strong>{m.value}</strong><small>{m.change && <b>{m.change}</b>} {m.detail}</small></div></article>)}</div>; }
function Donut({ total = '$12.85M', label = 'Total Value' }: { total?: string; label?: string }) { return <div className="donut"><div><strong>{total}</strong><span>{label}</span></div></div>; }
function Legend() { return <div className="legend">{['Tier 1 Conservative $4.28M (33.3%)','Tier 2 Balanced $4.17M (32.4%)','Tier 3 Aggressive $2.88M (22.5%)','Liquid Staking $1.01M (7.8%)','Cash / Stablecoin $0.50M (3.9%)'].map((x,i)=><span key={x}><i className={`dot d${i}`}/>{x}</span>)}</div>; }
function Trend({ multi = false, bar = false }: { multi?: boolean; bar?: boolean }) { const max = 34; return <div className="chart"><div className="axis"><span>30%</span><span>20%</span><span>10%</span><span>0%</span></div>{bar && <div className="bars">{bars.map((v,i)=><i key={i} style={{height:`${Math.max(10,v*4)}px`}} />)}</div>}<svg viewBox="0 0 520 220" preserveAspectRatio="none"><polyline points={lineData.map((v,i)=>`${i*(520/(lineData.length-1))},${220-(v/max)*190}`).join(' ')} /><polyline className="blue-line" points={blueData.map((v,i)=>`${i*(520/(blueData.length-1))},${220-(v/max)*190}`).join(' ')} />{multi && <polyline className="green-line" points={lineData.map((v,i)=>`${i*(520/(lineData.length-1))},${220-((v*.42)/max)*190}`).join(' ')} />}</svg><div className="chart-labels"><span>Apr 12</span><span>Apr 19</span><span>Apr 26</span><span>May 3</span><span>May 10</span></div></div>; }
function PoolTable({ compact = false }: { compact?: boolean }) { return <div className="table-wrap"><table><thead><tr><th>Pool</th><th>Tier / Risk</th><th>APY</th><th>TVL</th><th>Min.</th><th>Lock</th><th>Status</th><th></th></tr></thead><tbody>{pools.map(p=><tr key={p.name}><td><b>{p.name}</b><small>{p.description}</small></td><td><Pill accent={p.accent}>{p.risk}</Pill></td><td><b>{p.apy}</b><small className="up">+{compact?'1.32':'2.16'}%</small></td><td>{p.tvl}</td><td>{p.min}</td><td>{p.lock}</td><td><span className="live"/> {p.status}</td><td><button className={cx('mini-btn',p.accent)}>Invest Now</button></td></tr>)}</tbody></table></div>; }
function TxTable() { return <div className="table-wrap"><table><thead><tr><th>Date & Time</th><th>Type</th><th>Pool</th><th>Amount</th><th>Asset</th><th>Tx Hash</th><th>Status</th></tr></thead><tbody>{txs.concat(txs).slice(0,10).map((t,i)=><tr key={i}><td>{t.date}</td><td>{t.type}</td><td>{t.pool}</td><td>{t.amount}</td><td>{t.asset}</td><td><a>{t.hash}</a></td><td><Pill>Completed</Pill></td></tr>)}</tbody></table></div>; }
function DocTable({ tax = false }: { tax?: boolean }) { const rows = tax ? ['Form 1099-INT','Form 1099-MISC','Schedule D','Form 8949','Year-End Summary','2025 Estimated Tax Guide','Crypto Tax Reporting Guide'].map((name,i)=>({name,type:i<2?'Income':i<4?'Capital Gains/Losses':'Summary / Guide',period:'2025',generated:i<5?'Jan 15, 2025':'Jan 10, 2025',size:`${140+i*55} KB`,status:'Available'})) : docs; return <div className="table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Period</th><th>Generated</th><th>Size</th><th>Status</th><th></th></tr></thead><tbody>{rows.map((d:any)=><tr key={d.name}><td><b>{d.name}</b></td><td>{d.type}</td><td>{d.period}</td><td>{d.generated}</td><td>{d.size}</td><td><Pill>{d.status}</Pill></td><td><button className="icon-btn"><Download size={16}/></button></td></tr>)}</tbody></table></div>; }
function Controls() { return <div className="controls"><label><Search size={16}/><input placeholder="Search..." /></label><select><option>All Pools</option><option>Tier 1</option><option>Tier 2</option><option>Tier 3</option></select><select><option>All Status</option><option>Active</option><option>Completed</option></select><button><SlidersHorizontal size={16}/> Filters</button><button><Download size={16}/> Export</button></div>; }
function PageHeader({ title, subtitle, actions }: { title: string; subtitle: string; actions?: any }) { return <div className="page-head"><div><h1>{title}</h1><p>{subtitle}</p></div>{actions}</div>; }

function Overview() { return <><Metrics items={metrics.slice(0,4)}/><div className="grid three"><Card title="Portfolio Overview"><div className="split"><div><h3>$12.85M</h3><p><b className="up">+14.21%</b> vs last 30d</p><dl><dt>Total Invested</dt><dd>$10.97M</dd><dt>Total Returns</dt><dd>$1.88M</dd><dt>Available</dt><dd>$1.23M</dd></dl></div><Trend /></div></Card><Card title="Asset Allocation"><Donut/><Legend/><a>View Full Allocation →</a></Card><Card title="Account Summary"><dl><dt>Total Value Locked</dt><dd>$12.85M</dd><dt>Total Earned</dt><dd>$1.88M</dd><dt>Next Payout Date</dt><dd>May 20, 2025</dd><dt>Your Staking Rewards</dt><dd>2,450 ADF</dd></dl></Card></div><div className="grid two"><Card title="Available Investment Pools" action={<button>View All Pools</button>}><div className="pool-cards">{pools.slice(0,3).map(p=><article key={p.name} className="pool-card"><AppIcon icon={ShieldCheck} accent={p.accent}/><h3>{p.name}</h3><Pill accent={p.accent}>{p.risk}</Pill><Trend/><strong>{p.apy}</strong><button>Invest Now</button></article>)}</div></Card><Card title="Pool Performance (30D)"><Trend multi/><PoolTable compact/></Card></div><div className="grid three"><Card title="Recent Transactions"><TxTable/></Card><Card title="Yield & Payouts Summary"><h3>$1.88M</h3><p>Total Earned All Time</p><h3>8D : 14H : 32M</h3><p>Next payout countdown</p><button>View Payout Schedule</button></Card><Card title="Platform Health"><Health/></Card></div></>; }
function Pools() { return <><PageHeader title="Pools" subtitle="Diverse investment pools. Institutional-grade. Transparent risk."/><Metrics items={[{...metrics[0],label:'Total Value Locked (TVL)'},{label:'Total Pools',value:'18',detail:'Active investment pools',icon:Users,accent:'purple'},{...metrics[2],label:'Weighted Average APY'},{label:'Risk Distribution',value:'Low 38%',detail:'Medium 36% • High 26%',icon:ShieldCheck,accent:'orange'},{label:'Total Investors',value:'1,248',change:'+7.45%',detail:'vs last 30d',icon:BarChart3,accent:'cyan'}]}/><Controls/><div className="grid side"><Card><PoolTable/></Card><aside><Card title="Pool Allocation"><Donut/><Legend/></Card><Card title="Risk Distribution"><Donut total="$12.85M" label="Total TVL"/><Legend/></Card><Card title="Market & Platform Stats"><dl><dt>Total Loans Funded</dt><dd>$214.32M</dd><dt>Default Rate (30D)</dt><dd>1.24%</dd><dt>Avg. LTV</dt><dd>62.4%</dd></dl></Card></aside></div></>; }
function Investments() { return <><Metrics items={[{label:'Total Invested',value:'$10.97M',change:'+14.21%',detail:'vs last 30d',icon:Wallet,accent:'green'},metrics[1],{label:'Unrealized Gains',value:'$842.31K',change:'+12.48%',detail:'vs last 30d',icon:ShieldCheck,accent:'blue'},{label:'ROI All Time',value:'17.12%',change:'+2.35%',detail:'vs last 30d',icon:Landmark,accent:'orange'},metrics[4]]}/><div className="grid side"><Card title="My Investments"><PoolTable/></Card><aside><Card title="Investment Performance"><Trend multi/></Card><Card title="Asset Allocation"><Donut/><Legend/></Card><Card title="Investment Summary"><dl><dt>Total Invested</dt><dd>$10.97M</dd><dt>Total Returns</dt><dd>$1.88M</dd><dt>Average APY</dt><dd>18.62%</dd></dl></Card></aside></div><Card title="Recent Investment Activity"><TxTable/></Card></>; }
function Performance() { return <><PageHeader title="Performance Overview" subtitle="Track the performance of your investments across all pools."/><Metrics items={[metrics[0],{label:'Total Return (30D)',value:'$1.58M',change:'+14.21%',detail:'vs last 30d',icon:Sparkles,accent:'purple'},metrics[1],metrics[2],{label:'Win Rate',value:'82.4%',change:'+6.21%',detail:'vs last 30d',icon:Target,accent:'green'},{label:'Sharpe Ratio',value:'1.84',change:'+0.24',detail:'vs last 30d',icon:ShieldCheck,accent:'blue'}]}/><div className="grid side"><Card title="Performance Over Time"><Trend multi/></Card><aside><Card title="Performance Comparison"><div className="bars-horizontal"><span>My Portfolio <b>+14.21%</b></span><i style={{width:'96%'}}/><span>Benchmark <b>+9.18%</b></span><i style={{width:'70%'}}/><span>Tier 1 <b>+7.32%</b></span><i style={{width:'55%'}}/></div></Card><Card title="Monthly Returns Heatmap"><Heatmap/></Card></aside></div><Card title="Pool Performance Breakdown"><PoolTable compact/></Card><div className="grid three"><Card title="Performance Insights"><ul><li>Your portfolio outperformed benchmark by 5.03%.</li><li>Tier 2 Balanced is driving highest returns this month.</li><li>Consider rebalancing for risk-adjusted returns.</li></ul></Card><Card title="Recent Performance Alerts"><ul><li>Tier 1 reached 7.32% return in last 30 days.</li><li>New milestone: +14.21% 30D.</li></ul></Card><Card title="Reports"><DocTable/></Card></div></>; }
function Transactions() { return <><Metrics items={[{label:'Total Deposits',value:'$10.97M',change:'+14.21%',detail:'vs last 30d',icon:Download,accent:'green'},{label:'Total Payouts',value:'$1.88M',change:'+18.32%',detail:'vs last 30d',icon:Calendar,accent:'purple'},{label:'Total Rewards',value:'2,450 ADF',change:'+12.48%',detail:'vs last 30d',icon:ShieldCheck,accent:'blue'},{label:'Total Transactions',value:'156',change:'+8.73%',detail:'vs last 30d',icon:Receipt,accent:'orange'},{label:'Net Cash Flow',value:'$9.09M',change:'+13.65%',detail:'vs last 30d',icon:Activity,accent:'cyan'}]}/><PageHeader title="Transactions" subtitle="Track all deposits, payouts, rewards, and account activities."/><Controls/><div className="grid side"><Card><TxTable/></Card><aside><Card title="Transaction Breakdown"><Donut total="156" label="Total"/><Legend/></Card><Card title="Net Cash Flow"><h3>$9.09M</h3><Trend bar/></Card><Card title="Recent Activity"><ul>{txs.map(t=><li key={t.hash}>{t.type} — {t.pool} <b>{t.amount}</b></li>)}</ul></Card></aside></div></>; }
function Statements() { return <><Metrics items={[{label:'Total Deposits All Time',value:'$10.97M',change:'+14.21%',detail:'vs last 30d',icon:ShieldCheck,accent:'green'},{label:'Total Payouts All Time',value:'$1.88M',change:'+18.32%',detail:'vs last 30d',icon:Sparkles,accent:'purple'},{label:'Total Rewards All Time',value:'2,450 ADF',change:'+12.48%',detail:'vs last 30d',icon:Calendar,accent:'blue'},{label:'Net Cash Flow All Time',value:'$9.09M',change:'+13.65%',detail:'vs last 30d',icon:Activity,accent:'cyan'},{label:'Statements Generated',value:'24',detail:'Last 12 months',icon:FileText,accent:'blue'}]}/><PageHeader title="Statements" subtitle="View, download, and manage account statements and activity reports."/><Controls/><div className="grid side"><Card><DocTable/></Card><aside><Card title="Statement Overview"><Donut total="24" label="Total Statements"/><dl><dt>This Year</dt><dd>5</dd><dt>Last Statement</dt><dd>May 1, 2025</dd></dl></Card><Card title="Download Center"><button>Download All Statements</button><button>Generate Custom Statement</button></Card><Card title="Tax Information"><button>Year-to-Date Summary</button><button>Tax Documents Center</button></Card></aside></div></>; }
function Reports() { return <><Metrics items={[metrics[0],metrics[1],metrics[2],metrics[3],{label:'Reports Generated',value:'128',detail:'Last 12 months',icon:FileText,accent:'orange'}]}/><PageHeader title="Reports & Analytics" subtitle="Comprehensive insights, performance reports, and data-driven intelligence."/><Controls/><div className="grid side"><Card title="Performance Overview"><Trend multi/></Card><aside><Card title="Reports Summary"><Donut total="128" label="Total Reports"/><Legend/></Card><Card title="Popular Reports"><DocTable/></Card></aside></div><Card title="Report Categories"><div className="report-grid">{['Performance Reports','Transaction Reports','Statement Reports','Tax Reports','Custom Reports','Risk & Exposure'].map((r,i)=><article key={r}><AppIcon icon={[LineChart,Receipt,FileText,Receipt,SlidersHorizontal,ShieldCheck][i]} accent={['blue','green','purple','orange','cyan','slate'][i] as Accent}/><h3>{r}</h3><p>Generate and download investor-grade reporting.</p><button>Generate Report</button></article>)}</div></Card><Card title="Recent Reports"><DocTable/></Card></>; }
function Portfolio() { return <><Metrics items={[metrics[0],{label:'Total Invested',value:'$10.97M',detail:'',icon:Wallet,accent:'purple'},metrics[1],{label:'Unrealized Gains',value:'$842.31K',change:'+8.75%',detail:'vs last 30d',icon:BarChart3,accent:'orange'},metrics[4],metrics[2]]}/><div className="grid side"><div><Card title="Portfolio Value Over Time"><Trend/></Card><Card title="Your Investments"><PoolTable compact/></Card></div><aside><Card title="Portfolio Allocation"><Donut/><Legend/></Card><Card title="Portfolio Health"><Health/></Card><Card title="Next Payout"><h3>8D : 14H : 32M</h3><p>Estimated payout $24,580.32 USDC</p></Card></aside></div></>; }
function Allocation() { return <><Metrics items={[metrics[0],{label:'Total Invested',value:'$10.97M',icon:Wallet,accent:'purple'},{label:'Available to Invest',value:'$1.23M',icon:Users,accent:'green'},metrics[1],{label:'Allocation Score',value:'92/100',detail:'Excellent',icon:ShieldCheck,accent:'cyan'}]}/><PageHeader title="Allocation Overview" subtitle="Track how your capital is allocated across pools, tiers, and asset types."/><div className="grid three"><Card title="Allocation by Tier"><Donut/><Legend/></Card><Card title="Allocation by Asset Type"><Donut/><Legend/></Card><Card title="Allocation Heatmap"><Heatmap/></Card></div><div className="grid side"><Card title="Allocation by Pool"><PoolTable compact/></Card><aside><Card title="Allocation Insights"><ul><li>Well diversified across tiers and asset types.</li><li>Optimal tier balance aligns with your risk profile.</li><li>Strong yield potential from higher-yield strategies.</li><li>Consider increasing cash buffer to 5%–10%.</li></ul></Card><Card title="Allocation History"><Trend multi/></Card></aside></div></>; }
function YieldHistory() { return <><Metrics items={[metrics[2],metrics[1],{label:'This Month Yield',value:'$214,320.18',change:'+12.45%',detail:'vs last month',icon:BarChart3,accent:'green'},{label:'Best Performing Pool',value:'Tier 3 Aggressive',detail:'25.34% APY',icon:TrendingUp,accent:'purple'},{label:'Yield Days All Time',value:'476 Days',detail:'Since Jan 18, 2024',icon:Calendar,accent:'cyan'}]}/><PageHeader title="Yield History" subtitle="Track your yield performance over time across all pools and investments."/><Controls/><div className="grid side"><div><Card title="Yield Over Time"><Trend multi bar/></Card><Card title="Yield by Pool"><PoolTable compact/></Card></div><aside><Card title="Yield Summary"><dl><dt>Total Yield Earned</dt><dd>$214,320.18</dd><dt>Average Daily Yield</dt><dd>$7,154.01</dd><dt>Average APY</dt><dd>18.62%</dd><dt>Positive Yield Days</dt><dd>30 / 30</dd></dl></Card><Card title="Yield Distribution"><Donut total="$214.32K" label="Total Yield"/><Legend/></Card><Card title="Top Yield Days"><ul><li>May 3 — $22,841.35</li><li>May 6 — $18,742.63</li><li>May 8 — $17,923.18</li></ul></Card></aside></div></>; }
function Payouts() { return <><Metrics items={[{label:'Total Payouts All Time',value:'$2,450.68',change:'+18.36%',detail:'vs last 30d',icon:ShieldCheck,accent:'green'},{label:'This Month Payouts',value:'$214.32',change:'+12.45%',detail:'vs last month',icon:Calendar,accent:'blue'},{label:'Pending Payouts',value:'$37.86',detail:'2 Upcoming',icon:Calendar,accent:'purple'},{label:'Next Payout Date',value:'May 20, 2025',detail:'In 5 days',icon:Calendar,accent:'orange'},{label:'Payout Frequency',value:'Daily',detail:'Auto-Compounding',icon:Activity,accent:'green'}]}/><PageHeader title="Payouts" subtitle="Track and manage all payouts across your pools and investments."/><Controls/><div className="grid side"><Card><TxTable/></Card><aside><Card title="Payout Overview"><Donut total="$2,450.68" label="Total Payouts"/><Legend/></Card><Card title="Upcoming Payouts"><ul>{pools.slice(0,5).map(p=><li key={p.name}>May 20 — {p.name} <b>$18.73</b></li>)}</ul></Card><Card title="Payout Settings"><dl><dt>Payout Method</dt><dd>Auto-Compound</dd><dt>Minimum Threshold</dt><dd>$5.00</dd><dt>Email Notifications</dt><dd>Enabled</dd></dl></Card></aside></div></>; }
function Tax() { return <><Metrics items={[{label:'Total Tax Documents',value:'18',detail:'Available to download',icon:FileText,accent:'purple'},{label:'Tax Years Available',value:'4 Years',detail:'2025, 2024, 2023, 2022',icon:Calendar,accent:'blue'},{label:'Documents Downloaded',value:'7',detail:'This year',icon:Download,accent:'green'},{label:'Total Reported Income',value:'$214,320.18',detail:'Tax Year 2025',icon:CircleDollarSign,accent:'orange'},{label:'Total Capital Gains',value:'$86,745.62',detail:'Tax Year 2025',icon:PieChart,accent:'cyan'}]}/><PageHeader title="Tax Documents" subtitle="Download tax forms and reports for filing your taxes."/><Controls/><div className="grid side"><Card><DocTable tax/></Card><aside><Card title="Tax Year Summary (2025)"><dl><dt>Interest Income</dt><dd>$38,742.63</dd><dt>Staking Rewards</dt><dd>$21,957.55</dd><dt>Total Income</dt><dd>$60,700.18</dd><dt>Total Capital Gains</dt><dd>$86,745.62</dd></dl></Card><Card title="Important Information"><ul><li>Tax documents are based on on-chain activity and platform records.</li><li>Consult a tax professional for personalized advice.</li><li>Report income and gains to appropriate tax authorities.</li></ul></Card></aside></div></>; }
function How() { const steps=['Sourced & Underwritten','Tokenized on-Chain','Pooled & Diversified','Earn & Compounded','Track & Withdraw']; return <><PageHeader title="How AutoDeFi DAO Works" subtitle="Earn sustainable risk-adjusted returns by investing in real-world auto finance assets through transparent on-chain infrastructure."/><div className="steps">{steps.map((s,i)=><article key={s}><b>{i+1}</b><AppIcon icon={[Car,Globe2,PieChart,TrendingUp,Wallet][i]} accent={['purple','blue','cyan','green','purple'][i] as Accent}/><h3>{s}</h3><p>{['Vetted dealers and lenders originate high-quality auto loans with credit and fraud checks.','Approved loans are tokenized into digital assets and recorded on-chain for transparency.','Loans are grouped into diversified pools across risk tiers and asset types.','Investors earn daily yield from loan payments and auto-compounding strategies.','Monitor performance and withdraw capital and earnings through secure settlement.'][i]}</p></article>)}</div><div className="grid side"><Card title="Power of Real-World Assets on Blockchain"><div className="feature-grid"><Feature icon={ShieldCheck} title="Security & Transparency" text="Assets, transactions, and cash flows are recorded for auditability."/><Feature icon={LockKeyhole} title="Diversification at Scale" text="Access hundreds of auto loans across geographies and borrower profiles."/><Feature icon={Activity} title="Efficiency & Automation" text="Smart contracts automate yield distribution and reporting."/><Feature icon={Users} title="Community Governance" text="DAO members vote on proposals, treasury allocation, and risk parameters."/></div></Card><aside><Card title="Platform by the Numbers"><dl><dt>Total Value Locked</dt><dd>$12.85M</dd><dt>Active Pools</dt><dd>18</dd><dt>Total Investors</dt><dd>4,892</dd><dt>On-Time Payment Rate</dt><dd>97.23%</dd></dl></Card></aside></div></>; }
function Risk() { return <><PageHeader title="Risk Framework" subtitle="Understand how AutoDeFi manages risk to protect and grow capital."/><Metrics items={[{label:'Overall Risk Rating',value:'Low to Moderate',detail:'Well-managed risk across all dimensions',icon:ShieldCheck,accent:'green'},{label:'Risk Score',value:'28/100',detail:'Low',icon:Target,accent:'green'},{label:'Value at Risk 7D',value:'2.31%',detail:'95% confidence',icon:AlertTriangle,accent:'orange'},{label:'Stress Test',value:'-8.42%',detail:'2020 market crash simulation',icon:Activity,accent:'red'},{label:'Max Historical Drawdown',value:'-12.87%',detail:'Duration 38 days',icon:LineChart,accent:'red'}]}/><div className="grid side"><Card title="Risk Overview"><div className="radar"><div>Smart Contract</div><div>Market</div><div>Liquidity</div><div>Counterparty</div><div>Operational</div></div><PoolTable compact/></Card><aside><Card title="Risk Heatmap"><Heatmap/><ul><li>Market Volatility</li><li>Borrower Default</li><li>Smart Contract Failure</li><li>Liquidity Shortfall</li></ul></Card><Card title="Risk Limits & Controls"><div className="limits"><span>Max LTV <b>65%</b></span><i style={{width:'65%'}}/><span>Max Borrower Exposure <b>6.2%</b></span><i style={{width:'42%'}}/><span>Liquidity Coverage <b>2.48x</b></span><i style={{width:'82%'}}/></div></Card><Card title="Risk Disclosures"><p>Investing involves risk, including potential loss of principal. Past performance is not indicative of future results.</p></Card></aside></div></>; }
function Docs() { const items=['Getting Started with AutoDeFi DAO','Understanding Auto Finance Pools','Smart Contract Architecture','Security Overview & Best Practices','Q1 2025 Transparency Report','AutoDeFi DAO Terms of Service','Frequently Asked Questions']; return <><PageHeader title="Documentation" subtitle="Explore guides, technical docs, and resources."/><div className="searchbar"><Search/><input placeholder="Search documentation..."/></div><div className="report-grid">{['Getting Started','Platform Guide','Protocols & Smart Contracts','Security & Audits','Reports & Policies'].map((r,i)=><article key={r}><AppIcon icon={[BookOpen,LayoutDashboard,Globe2,ShieldCheck,FileText][i]} accent={['green','blue','purple','cyan','orange'][i] as Accent}/><h3>{r}</h3><p>Documentation and guides for the investor portal.</p><button>View Guides</button></article>)}</div><div className="grid side"><Card title="Popular Documentation"><div className="table-wrap"><table><tbody>{items.map((x,i)=><tr key={x}><td><b>{x}</b><small>{i%2?'Technical reference and platform details.':'Beginner guide and investor walkthrough.'}</small></td><td><Pill accent={i%3===0?'green':i%3===1?'blue':'purple'}>{i%3===0?'Guide':i%3===1?'Platform':'Technical'}</Pill></td><td>May {8-i}, 2025</td><td><button className="icon-btn"><Download size={16}/></button></td></tr>)}</tbody></table></div></Card><aside><Card title="Getting Started"><ol><li>Create your account</li><li>Deposit capital</li><li>Choose a pool</li><li>Start earning</li></ol></Card><Card title="API & Integrations"><ul><li>API Documentation</li><li>Webhooks</li><li>Developer Resources</li></ul></Card></aside></div></>; }
function Help() { const topics=['Getting Started','Investing','Earnings & Yields','Payouts','Account & Security','Taxes','Platform & Features','Troubleshooting']; return <><PageHeader title="Help Center" subtitle="Find answers, guides, and support for AutoDeFi DAO."/><div className="searchbar"><Search/><input placeholder="Search for articles, topics, or questions..."/></div><div className="topic-grid">{topics.map((t,i)=><article key={t}><AppIcon icon={[Sparkles,PieChart,BarChart3,Wallet,ShieldCheck,Receipt,Globe2,HelpCircle][i]} accent={['purple','green','orange','blue','purple','green','cyan','orange'][i] as Accent}/><h3>{t}</h3><p>{6+i} articles</p><ChevronRight/></article>)}</div><div className="grid side"><Card title="Frequently Asked Questions"><Faq/></Card><aside><Card title="Contact Support"><SupportOptions/></Card><Card title="System Status"><h3><span className="live"/> All Systems Operational</h3><p>All platform systems are running smoothly.</p></Card><Card title="Popular Guides"><ul><li>How to Get Started</li><li>Understanding Auto Finance Pools</li><li>How Yields and Compounding Work</li><li>Tax Guide for AutoDeFi Investors</li></ul></Card></aside></div></>; }
function Contact() { const [sent,setSent]=useState(false); async function submit(e:any){e.preventDefault(); const form=new FormData(e.currentTarget); try{ await fetch(`${apiBase()}/api/support/tickets`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))}); }catch{} setSent(true); } return <><PageHeader title="Contact Support" subtitle="Submit a request and we will get back to you as soon as possible."/><div className="grid side"><Card title="Submit a Support Request"><form className="support-form" onSubmit={submit}><label>What can we help you with?<select name="category"><option>Investment question</option><option>Wallet / account</option><option>Payouts</option><option>Tax documents</option><option>Technical issue</option></select></label><label>Subject<input name="subject" placeholder="Briefly describe your issue" required/></label><label>Description<textarea name="description" rows={7} placeholder="Please provide as much detail as possible..." required/></label><label>Account / Wallet<input name="wallet" placeholder="0x7a8B...EF23"/></label><button className="deposit" type="submit">Submit Request</button>{sent && <Pill>Support request submitted</Pill>}</form></Card><aside><Card title="Other Ways to Reach Us"><SupportOptions/><div className="hours"><h3>Support Hours</h3><p>Monday – Friday 8:00 AM – 8:00 PM UTC</p><p>Saturday – Sunday 10:00 AM – 6:00 PM UTC</p></div></Card><Card title="Before You Contact Us"><ul><li>How to Deposit Funds</li><li>How to Withdraw Funds</li><li>Understanding Yield & APY</li><li>Payout Schedule & Frequency</li><li>KYC Verification Guide</li></ul></Card><Card title="Urgent Help"><p>For security issues or account access problems, use Live Chat or Email Support.</p></Card></aside></div></>; }
function Feature({ icon, title, text }: { icon:any; title:string; text:string }) { return <article className="feature"><AppIcon icon={icon}/><div><h3>{title}</h3><p>{text}</p></div></article>; }
function Heatmap() { return <div className="heatmap">{Array.from({length:20}).map((_,i)=><span key={i} className={`h${i%5}`}>{i%4===0?`${18+i}.7%`:''}</span>)}</div>; }
function Health() { return <dl><dt>Platform Utilization</dt><dd>78.6% <Pill>Healthy</Pill></dd><dt>Insurance Coverage</dt><dd>92.1% <Pill>Strong</Pill></dd><dt>Reserve Ratio</dt><dd>1.87x <Pill>Strong</Pill></dd><dt>Delinquency Rate</dt><dd>1.24% <Pill>Low</Pill></dd><dt>Smart Contract Security</dt><dd>100% <Pill>Secured</Pill></dd></dl>; }
function Faq() { return <div className="faq">{['What is AutoDeFi DAO and how does it work?','How do I invest in a pool?','How are yields calculated and paid?','When are payouts distributed?','How do I withdraw my funds?','Is my investment safe?'].map(q=><details key={q}><summary>{q}</summary><p>AutoDeFi DAO connects investor capital to tokenized real-world auto finance assets with transparent pool-level reporting and risk controls.</p></details>)}</div>; }
function SupportOptions() { return <div className="support-options"><a><MessageCircle/> Live Chat <ChevronRight/></a><a><Mail/> Email Support <ChevronRight/></a><a><Calendar/> Schedule a Call <ChevronRight/></a><a><Users/> Community Forum <ChevronRight/></a></div>; }

const pages: Record<PageKey, { title: string; subtitle: string; component: any }> = {
  overview: { title: 'Overview', subtitle: 'Investor command center for AutoDeFi DAO capital, yield, and risk.', component: Overview },
  pools: { title: 'Pools', subtitle: 'Diverse investment pools across risk tiers.', component: Pools },
  investments: { title: 'Investments', subtitle: 'Track and manage active investments.', component: Investments },
  performance: { title: 'Performance', subtitle: 'Portfolio and pool performance analytics.', component: Performance },
  transactions: { title: 'Transactions', subtitle: 'Deposits, payouts, rewards, and transfers.', component: Transactions },
  statements: { title: 'Statements', subtitle: 'Account statements and activity summaries.', component: Statements },
  reports: { title: 'Reports', subtitle: 'Investor reports and analytics.', component: Reports },
  portfolio: { title: 'My Portfolio', subtitle: 'Your current allocations and yield position.', component: Portfolio },
  allocation: { title: 'Allocation', subtitle: 'Capital allocation across pools and tiers.', component: Allocation },
  yield: { title: 'Yield History', subtitle: 'Yield, APY, and payout trends.', component: YieldHistory },
  payouts: { title: 'Payouts', subtitle: 'Track and manage payout schedules.', component: Payouts },
  tax: { title: 'Tax Documents', subtitle: 'Tax forms and filing support documents.', component: Tax },
  how: { title: 'How It Works', subtitle: 'Learn how AutoDeFi DAO converts auto finance into transparent on-chain yield.', component: How },
  risk: { title: 'Risk Framework', subtitle: 'Risk controls, stress tests, limits, and disclosures.', component: Risk },
  docs: { title: 'Documentation', subtitle: 'Guides, API docs, security resources, and policies.', component: Docs },
  help: { title: 'Help Center', subtitle: 'Knowledge base and support resources.', component: Help },
  contact: { title: 'Contact Support', subtitle: 'Reach the AutoDeFi DAO support team.', component: Contact }
};

export function App() {
  const [active, setActive] = useState<PageKey>('overview');
  const Page = useMemo(() => pages[active].component, [active]);
  useEffect(() => { const load = async () => { if (import.meta.env.VITE_USE_FIXTURE_DATA === 'true') return; try { await fetch(`${apiBase()}/api/investor/dashboard`); } catch {} }; load(); }, []);
  return <div className="app-shell"><aside className="sidebar"><button className="brand" onClick={()=>setActive('overview')}><span>AD</span><b>AUTODEFI <em>DAO</em><small>INVESTOR PORTAL</small></b></button>{navGroups.map(g=><nav key={g.label}><p>{g.label}</p>{g.items.map(({key,label,icon:Icon})=><button key={key} className={active===key?'active':''} onClick={()=>setActive(key)}><Icon size={17}/>{label}</button>)}</nav>)}<section className="tier"><div className="diamond">◇</div><span>Your Investor Tier</span><strong>DIAMOND</strong><ul><li>Priority Support</li><li>Lower Fees</li><li>Early Access</li><li>Higher Limits</li></ul><button>View Benefits</button></section></aside><main><header className="top"><div><span>Welcome back,</span><h2>Visionary Investor <b>◆</b></h2><p>{pages[active].subtitle}</p></div><div className="top-actions"><a className="chip">ADF <strong>$0.8724</strong> <b>+4.32%</b></a><button className="bell"><Bell/><i>12</i></button><a className="wallet"><span/>0x7a8B...EF23<small>Connected</small></a><a className="deposit" href={import.meta.env.VITE_DEPOSIT_URL || '/investor/deposit'}>Deposit Capital</a></div></header>{active !== 'overview' && active !== 'pools' && active !== 'performance' && active !== 'transactions' && active !== 'statements' && active !== 'reports' && active !== 'allocation' && active !== 'yield' && active !== 'payouts' && active !== 'tax' && active !== 'how' && active !== 'risk' && active !== 'docs' && active !== 'help' && active !== 'contact' ? <PageHeader title={pages[active].title} subtitle={pages[active].subtitle}/> : null}<Page/><footer className="trust"><Feature icon={ShieldCheck} title="Institutional Grade Security" text="Audited smart contracts & multi-sig custody"/><Feature icon={Car} title="Real World Assets" text="Backed by real auto loans & collateral"/><Feature icon={Globe2} title="Transparent & On-Chain" text="Every transaction. Every time."/><Feature icon={Users} title="DAO Governed" text="Community owned. Community driven."/><Feature icon={TrendingUp} title="Revenue Sharing" text="Real yield. Real value. Real rewards."/></footer></main></div>;
}
